name: Build Windows EXE

on:
  push:
    branches: [ main ]          # يتم البناء عند كل Push
  workflow_dispatch:            # أو يدويًا من تبويب Actions

permissions:
  contents: write               # للسماح برفع الـ Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. جلب الكود
    - uses: actions/checkout@v3

    # 2. إعداد بايثون
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. تثبيت المكتبات
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pyqt5 pyqtwebengine pyserial requests matplotlib numpy

    # 4. بناء ملف EXE مع كل الموارد المطلوبة
    - name: Build EXE
      run: >
        pyinstaller --onefile --windowed --name improved_ui
        --hidden-import serial
        --add-data "images;images"
        --add-data "flags;flags"
        --add-data "MessageConfig;MessageConfig"
        --add-data "config.ini;."
        --add-data "constellation.html;."
        --collect-all PyQt5.QtWebEngineWidgets
        --collect-all PyQt5.QtWebEngineCore
        improved_ui.py

    # 5. رفع الملف إلى صفحة Releases
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: build-${{ github.run_number }}
        body: Auto build
        files: dist/improved_ui.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
