name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write               # كي يتمكّن من رفع الـ Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1) جلب الكود
    - uses: actions/checkout@v3

    # 2) إعداد بايثون
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3) تثبيت PyInstaller والمكتبات المطلوبة
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller           # ← PyInstaller أولاً
        python -m pip install pyqt5 pyqtwebengine
        python -m pip install pyserial requests
        python -m pip install matplotlib numpy

    # 4) بناء ملف EXE
    - name: Build EXE
      run: |
        pyinstaller --version               # للتأكد
        pyinstaller --onefile --name improved_ui
          --add-data "images;images"
          --add-data "flags;flags"
          improved_ui.py


    # 5) رفعه إلى صفحة Releases
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: build-${{ github.run_number }}
        body: Auto build
        files: dist/improved_ui.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
